### ISSUE TITLE
default branch doesn't compile, and it's unclear how it ever could

### ISSUE THREAD

**Issue by Mis012** [andestech/nds-openocd#3]
compiling with gcc/clang on Linux results in a wall of errors on the final linking step, such as:
```
... multiple definition of `ndsv5_l2c_support' ...
... multiple definition of `nds_dmi_quick_access' ...
... undefined reference to `user_algorithm_path' ...
... undefined reference to `algorithm_bin_read' ...
```
The multiple definition errors seem to be caused by defining global variables in header files, instead of defining them once in one `.c` file and putting `extern` declarations in the header file.

Is this clearly incorrect C code supposed to compile, and if so, on which complier?

**Comment by twpedersen** [comment]
+1, any hints on how to build this with gcc?

**Comment by jhermit** [comment]
We will fix this issue on next release

**Comment by jhermit** [comment]
The bug has been fixed on the ast-v5_2_0-branch branch, and GCC-12 can now be used to build.
